### ISSUE TITLE
Transladar info al repo

### ISSUE THREAD

**Issue by IsmaelCaballero** [LauraToledoGutierrez/ISO22-ISO2-BC4#22]
Hola @LauraToledoGutierrez y equipo
Estoy viendo la wiki y os paso algunos comentarios:

- Veo que tenéis mucha info en ficheros aparte (por ejemplo Requisitos funcionales)... por favor, moved toda esa info a la propia wiki para que sea más fácil seguirla... incluyendo 
- No consigo ver cuántas aplicaciones estáis haciendo... tampoco la vista de los componentes por cada aplicación.
- No he visto los criterios para asignar versiones a los componentes
- Más detalles sobre las ramas (al menos un primero boceto)
- Me resulta rarísimo la organización que estáis haciendo con las carpetas en el código (eso de Análisis / Diseño/ Implementación/Pruebas me resulta muy raro... antes de nada, prefiero preguntar... ;)

Seguiré mirando cosas
Saludos
Ismael

**Comment by LauraToledoGutierrez** [comment]
Hola, creo que justo cuando le estabas echando un ojo al repositorio estábamos cambiando cosillas.
Lo de las ramas esta en la parte de gestión de configuración y lo de la organización en carpetas, te refieres a que las quitemos y dejemos los archivos sueltos en cada iteración?

Enviado desde Correo<https://go.microsoft.com/fwlink/?LinkId=550986> para Windows

De: Ismael ***@***.***>
Enviado: jueves, 17 de noviembre de 2022 19:53
Para: ***@***.***>
CC: LAURA TOLEDO ***@***.***>; ***@***.***>
Asunto: [LauraToledoGutierrez/ISO22-ISO2-BC4] Transladar info al repo (Issue #22)


Hola @LauraToledoGutierrez<https://github.com/LauraToledoGutierrez> y equipo
Estoy viendo la wiki y os paso algunos comentarios:

  *   Veo que tenéis mucha info en ficheros aparte (por ejemplo Requisitos funcionales)... por favor, moved toda esa info a la propia wiki para que sea más fácil seguirla... incluyendo
  *   No consigo ver cuántas aplicaciones estáis haciendo... tampoco la vista de los componentes por cada aplicación.
  *   No he visto los criterios para asignar versiones a los componentes
  *   Más detalles sobre las ramas (al menos un primero boceto)
  *   Me resulta rarísimo la organización que estáis haciendo con las carpetas en el código (eso de Análisis / Diseño/ Implementación/Pruebas me resulta muy raro... antes de nada, prefiero preguntar... ;)

Seguiré mirando cosas
Saludos
Ismael

**Comment by IsmaelCaballero** [comment]
Okis, pues entonces cuando terminéis los cambios me avisáis y le echo otro ojo
Muchas gracias!

**Comment by LauraToledoGutierrez** [comment]
Ya esta terminada la reunión! 😊

Enviado desde Correo<https://go.microsoft.com/fwlink/?LinkId=550986> para Windows

De: Ismael ***@***.***>
Enviado: jueves, 17 de noviembre de 2022 20:16
Para: ***@***.***>
CC: LAURA TOLEDO ***@***.***>; ***@***.***>
Asunto: Re: [LauraToledoGutierrez/ISO22-ISO2-BC4] Transladar info al repo (Issue #22)


Okis, pues entonces cuando terminéis los cambios me avisáis y le echo otro ojo
Muchas gracias!
